[package]
name = "codex32"
version = "0.1.0"
edition = "2018"
description = "Python3 reference implementation of the codex32 spec"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
